mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('ads/', include('ads.urls')),

    # Sample applications
    # path('hello/', include('hello.urls')),
    # path('users/', include('users.urls')),
    # path('tracks/', include('tracks.urls')),
    # path('views/', include('views.urls')),
    # path('route/', include('route.urls', namespace='nsroute')),
    # path('tmpl/', include('tmpl.urls')),
    # path('gview/', include('gview.urls')),
    # path('session/', include('session.urls')),
    # path('authz/', include('authz.urls')),
    # path('getpost/', include('getpost.urls')),
    # path('form/', include('form.urls')),
    # path('crispy/', include('crispy.urls')),
    # path('myarts/', include('myarts.urls')),
    # path('menu/', include('menu.urls')),
    # path('forums/', include('forums.urls')),
    # path('pics/', include('pics.urls')),
    # path('favs/', include('favs.urls')),
    # path('favsql/', include('favsql.urls')),
    # path('rest/', include('rest.urls')),
    # path('autos/', include('autos.urls')),
    # path('usermodel/', include('usermodel.urls')),
    # path('chat/', include('chat.urls')),
    # path('util/', include('util.urls')),
    # path('well/', include('well.urls')),
    # path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/wizards/urls.py
from django.urls import path
from . import views

app_name = 'wizards'
urlpatterns = [
    path('', views.MainView.as_view(),name='all'),
    path('main/create/', views.WizardCreate.as_view(), name='wizard_create'),
    path('main/<int:pk>/update/', views.WizardUpdate.as_view(), name='wizard_update'),
    path('main/<int:pk>/delete', views.WizardDelete.as_view(), name='wizard_delete'),
    path('lookup/', views.HouseView.as_view(), name='house_list'),
    path('lookup/create/', views.HouseCreate.as_view(), name='house_create'),
    path('lookup/<int:pk>/update', views.HouseUpdate.as_view(), name='house_update'),
    path('lookup/create/<int:pk>/delete', views.HouseDelete.as_view(), name='house_delete'),
]

mysite/wizards/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.core.validators import MinLengthValidator


class House(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "House must be greater than 1 character")]
    )

    def __str__(self):
        return self.name


class Wizard(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "Nickname must be greater than 1 character")]
    )
    power = models.PositiveIntegerField()
    spell = models.CharField(max_length=300)
    house = models.ForeignKey('House', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

mysite/wizards/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Wizard, House
# Create your views here.


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        hc = House.objects.all().count()
        wl = Wizard.objects.all()

        wtx = {'house_count': hc, 'wizard_list': wl}
        return render(request, 'wizards/wizards_list.html', wtx)


class HouseView(LoginRequiredMixin, View):
    def get(self, request):
        hl = House.objects.all()
        wtx = {'house_list': hl}
        return render(request, 'wizards/house_list.html', wtx)


class WizardCreate(LoginRequiredMixin, CreateView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')


class WizardUpdate(LoginRequiredMixin, UpdateView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')


class WizardDelete(LoginRequiredMixin, DeleteView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')


class HouseCreate(LoginRequiredMixin, CreateView):
    model = House
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')


class HouseUpdate(LoginRequiredMixin, UpdateView):
    model = House
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')


class HouseDelete(LoginRequiredMixin, DeleteView):
    model = House
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')

mysite/home/templates/wizards/house_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete House</h1>

<p>Are you sure you want to delete the house: {{ house }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'wizards:all' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

mysite/home/templates/wizards/house_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'wizards:all' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/home/templates/wizards/house_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>House List</h1>
{% if house_list %}
<ul>
  {% for house in house_list %}
  <li>
    {{ house.name }} (
    <a href="{% url 'wizards:house_update' house.id %}">Update</a>
    |
    <a href="{% url 'wizards:house_delete' house.id %}">Delete</a>
    )
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no houses in the library.</p>
{% endif %}
<p><a href="{% url 'wizards:house_create' %}">Add a house</a></p>
<p>
  <a href="{% url 'wizards:all' %}">Back to wizards</a>
</p>
{% endblock %}

mysite/home/templates/wizards/wizard_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete Auto</h1>

<p>Are you sure you want to delete the wizard: {{ wizard }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'wizards:all' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

mysite/home/templates/wizards/wizard_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'wizards:all' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/home/templates/wizards/wizards_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>Wizard List</h1>
{% if wizard_list %}
<ul>
  {% for wizard in wizard_list %}
  <li>
    {{ wizard.nickname }} ({{ wizard.house }}) (
    <a href="{% url 'wizards:wizard_update' wizard.id %}">Update</a>
    |
    <a href="{% url 'wizards:wizard_delete' wizard.id %}">Delete</a>
    )
    <br />
    {{ wizard.power }} ({{ wizard.spell }})
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no wizards in the library.</p>
{% endif %}
<p>
  {% if house_count > 0 %}
  <a href="{% url 'wizards:wizard_create' %}">Add a wizard</a>
  {% else %} Please add a house before you add an wizard. {% endif %}
</p>
<p>
  <a href="{% url 'wizards:house_list' %}">View houses</a>
  ({{ house_count }}) |
  <a href="{% url 'wizards:house_create' %}">Add a house</a>
</p>
{% endblock %}