mysite/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
         views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
         views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
         views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

mysite/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
    path('ads/', include('ads.urls')),

    # Sample applications
    # path('hello/', include('hello.urls')),
    # path('users/', include('users.urls')),
    # path('tracks/', include('tracks.urls')),
    # path('views/', include('views.urls')),
    # path('route/', include('route.urls', namespace='nsroute')),
    # path('tmpl/', include('tmpl.urls')),
    # path('gview/', include('gview.urls')),
    # path('session/', include('session.urls')),
    # path('authz/', include('authz.urls')),
    # path('getpost/', include('getpost.urls')),
    # path('form/', include('form.urls')),
    # path('crispy/', include('crispy.urls')),
    # path('myarts/', include('myarts.urls')),
    # path('menu/', include('menu.urls')),
    # path('forums/', include('forums.urls')),
    # path('pics/', include('pics.urls')),
    # path('favs/', include('favs.urls')),
    # path('favsql/', include('favsql.urls')),
    # path('rest/', include('rest.urls')),
    # path('autos/', include('autos.urls')),
    # path('usermodel/', include('usermodel.urls')),
    # path('chat/', include('chat.urls')),
    # path('util/', include('util.urls')),
    # path('well/', include('well.urls')),
    # path('tagme/', include('tagme.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

mysite/stars/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'stars'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.StarCreate.as_view(), name='star_create'),
    path('main/<int:pk>/update', views.StarUpdate.as_view(), name='star_update'),
    path('main/<int:pk>/delete', views.StarDelete.as_view(), name='star_delete'),
    path('lookup/', views.TypeView.as_view(), name='type_list'),
    path('lookup/create', views.TypeCreate.as_view(), name='type_create'),
    path('lookup/<int:pk>/update', views.TypeUpdate.as_view(), name='type_update'),
    path('lookup/<int:pk>/delete', views.TypeDelete.as_view(), name='type_delete'),
]

mysite/stars/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.core.validators import MinLengthValidator


class Type(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "Type must be greater than 1 character")]
    )

    def __str__(self):
        return self.name


class Star(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "Nickname must be greater than 1 character")]
    )
    mass = models.PositiveIntegerField()
    distance = models.PositiveIntegerField()
    type = models.ForeignKey('Type', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

mysite/stars/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Star, Type
# Create your views here.


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        type_count = Type.objects.all().count()
        stars = Star.objects.all()

        stars_info = {'type_count': type_count, 'star_list': stars}
        return render(request, 'stars/stars_list.html', stars_info)


class TypeView(LoginRequiredMixin, View):
    def get(self, request, *args):
        types = Type.objects.all()
        types_info = {'type_list': types}
        return render(request, 'stars/type_list.html', types_info)


class StarCreate(LoginRequiredMixin, CreateView):
    model = Star
    fields = '__all__'
    success_url = reverse_lazy('stars:all')


class StarUpdate(LoginRequiredMixin, UpdateView):
    model = Star
    fields = '__all__'
    success_url = reverse_lazy('stars:all')


class StarDelete(LoginRequiredMixin, DeleteView):
    model = Star
    fields = '__all__'
    success_url = reverse_lazy('stars:all')


class TypeCreate(LoginRequiredMixin, CreateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('stars:all')


class TypeUpdate(LoginRequiredMixin, UpdateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('stars:all')


class TypeDelete(LoginRequiredMixin, DeleteView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('stars:all')

mysite/home/templates/stars/star_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete Star</h1>

<p>Are you sure you want to delete the star: {{ star }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'stars:all' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

mysite/home/templates/stars/star_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'stars:all' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/home/templates/stars/stars_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>Stars List</h1>
{% if star_list %}
<ul>
  {% for star in star_list %}
  <li>
    {{ star.nickname }} ({{ star.type }}) (
    <a href="{% url 'stars:star_update' star.id %}">Update</a>
    |
    <a href="{% url 'stars:star_delete' star.id %}">Delete</a>
    )
    <br />
    {{ star.distance }} ({{ star.mass }} miles)
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no autos in the library.</p>
{% endif %}
<p>
  {% if type_count > 0 %}
  <a href="{% url 'stars:star_create' %}">Add a star</a>
  {% else %} Please add a type before you add a star. {% endif %}
</p>
<p>
  <a href="{% url 'stars:type_list' %}">View types</a>
  ({{ type_count }}) |
  <a href="{% url 'stars:type_create' %}">Add a type</a>
</p>
{% endblock %}

mysite/home/templates/stars/type_confirm_delete.html
{% extends "base_bootstrap.html" %} {% block content %}

<h1>Delete Type</h1>

<p>Are you sure you want to delete the type: {{ type }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
  <input
    type="submit"
    onclick="window.location='{% url 'stars:all' %}' ; return false;"
    value="Cancel"
  />
</form>

{% endblock %}

mysite/home/templates/stars/type_form.html
{% extends "base_bootstrap.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
  <input
    type="submit"
    onclick="window.location='{% url 'stars:all' %}' ; return false;"
    value="Cancel"
  />
</form>
{% endblock %}

mysite/home/templates/stars/type_list.html
{% extends "base_bootstrap.html" %} {% block content %}
<h1>Type List</h1>
{% if type_list %}
<ul>
  {% for type in type_list %}
  <li>
    {{ type.name }} (
    <a href="{% url 'stars:type_update' type.id %}">Update</a>
    |
    <a href="{% url 'stars:type_delete' type.id %}">Delete</a>
    )
  </li>
  {% endfor %}
</ul>
{% else %}
<p>There are no types in the library.</p>
{% endif %}
<p><a href="{% url 'stars:type_create' %}">Add a type</a></p>
<p>
  <a href="{% url 'stars:all' %}">Back to stars</a>
</p>
{% endblock %}